import {
  BRAIN_CONTRACT_VERSION,
  type BrainProjection,
} from "./brain-contracts";

const observeOnly = {
  canOpen: true,
  canInspectEvidence: true,
  canPrepareAction: false,
  canExecute: false,
  canApprove: false,
  actionCeiling: "observe" as const,
  approvalRequirement: "None" as const,
};

export const visualBrainDemo: BrainProjection = {
  contractVersion: BRAIN_CONTRACT_VERSION,
  generatedAt: "2026-09-22T23:45:00-06:00",
  mode: "demo",
  synthetic: true,
  context: {
    mode: "organization",
    scopeRef: "demo:dreamcatcher",
    organizationRef: "demo:atrapasuenos",
    workspaceRef: "demo:dreamcatcher-workspace",
    isolationMode: "private",
  },
  nodes: [
    {
      id: "node:dreamcatcher",
      kind: "organization",
      label: "Dreamcatcher Hotel",
      scopeRef: "demo:dreamcatcher",
      status: "Active",
      risk: "Low",
      verification: "verified",
      freshness: "current",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "synthetic_fixture",
      capabilities: observeOnly,
      activity: "idle",
      health: "healthy",
      summary: "Reference business context for the Visual Brain simulation.",
    },
    {
      id: "node:toro-finance",
      kind: "agent",
      label: "TORO Finance",
      scopeRef: "demo:dreamcatcher",
      status: "Active",
      risk: "Medium",
      verification: "verified",
      freshness: "current",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "TORO Brain",
      capabilities: {
        ...observeOnly,
        canPrepareAction: true,
        actionCeiling: "recommend",
        approvalRequirement: "Human review",
      },
      activity: "analyzing",
      health: "healthy",
      summary: "Comparing revenue, collections, accounting evidence and obligations.",
    },
    {
      id: "node:kross",
      kind: "connector",
      label: "Kross PMS",
      scopeRef: "demo:dreamcatcher",
      status: "Ready",
      risk: "Low",
      verification: "verified",
      freshness: "current",
      sourceSystem: "Kross",
      authoritySystem: "Kross",
      capabilities: observeOnly,
      activity: "reading",
      health: "healthy",
      summary: "Synthetic reservation and collections signal.",
    },
    {
      id: "node:alegra",
      kind: "connector",
      label: "Alegra",
      scopeRef: "demo:dreamcatcher",
      status: "Review",
      risk: "Medium",
      verification: "partially_verified",
      freshness: "aging",
      sourceSystem: "Alegra",
      authoritySystem: "Alegra",
      capabilities: observeOnly,
      activity: "reading",
      health: "degraded",
      summary: "Accounting evidence is older than the current PMS snapshot.",
    },
    {
      id: "node:revenue",
      kind: "kpi",
      label: "Reservations",
      scopeRef: "demo:dreamcatcher",
      status: "Ready",
      risk: "Low",
      verification: "verified",
      freshness: "current",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "Kross",
      capabilities: observeOnly,
      activity: "completed",
      summary: "Reservation value increased versus the comparison window.",
      metric: { label: "Change", value: 18.2, unit: "%" },
    },
    {
      id: "node:cash",
      kind: "kpi",
      label: "Cash coverage",
      scopeRef: "demo:dreamcatcher",
      status: "Review",
      risk: "High",
      verification: "partially_verified",
      freshness: "aging",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "Finance evidence",
      capabilities: observeOnly,
      activity: "completed",
      summary: "Collections are not rising at the same pace as booked revenue.",
      metric: { label: "Change", value: -7.4, unit: "%" },
    },
    {
      id: "node:bank-evidence",
      kind: "evidence",
      label: "Bank reconciliation",
      scopeRef: "demo:dreamcatcher",
      status: "Review",
      risk: "Medium",
      verification: "verified",
      freshness: "current",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "Bank evidence",
      capabilities: observeOnly,
      activity: "completed",
      health: "healthy",
      summary: "Synthetic evidence confirms a short-term cash timing gap.",
    },
    {
      id: "node:construction",
      kind: "project",
      label: "Construction closeout",
      scopeRef: "demo:dreamcatcher",
      status: "Active",
      risk: "Medium",
      verification: "partially_verified",
      freshness: "aging",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "TORO Projects",
      capabilities: observeOnly,
      activity: "idle",
      summary: "Open spend competes with short-term cash needs.",
      metric: { label: "Completion", value: 76, unit: "%" },
    },
    {
      id: "node:capex-approval",
      kind: "approval",
      label: "CAPEX approval",
      scopeRef: "demo:dreamcatcher",
      status: "Queued",
      risk: "High",
      verification: "unverified",
      freshness: "current",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "TORO Governance",
      capabilities: {
        ...observeOnly,
        canApprove: true,
        actionCeiling: "execute_with_approval",
        approvalRequirement: "Owner approval",
      },
      activity: "approval_required",
      summary: "Pause non-essential spend until the cash timing gap is verified.",
    },
    {
      id: "node:decision",
      kind: "decision",
      label: "Protect cash",
      scopeRef: "demo:dreamcatcher",
      status: "Draft",
      risk: "Medium",
      verification: "unverified",
      freshness: "current",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "TORO Brain",
      capabilities: {
        ...observeOnly,
        canPrepareAction: true,
        actionCeiling: "draft",
        approvalRequirement: "Owner approval",
      },
      activity: "waiting",
      summary: "Prepared decision: protect cash before approving additional discretionary spend.",
    },
  ],
  edges: [
    { id: "edge:org-finance", source: "node:dreamcatcher", target: "node:toro-finance", relation: "connected_to", verification: "verified", freshness: "current" },
    { id: "edge:finance-kross", source: "node:toro-finance", target: "node:kross", relation: "reads_from", verification: "verified", freshness: "current" },
    { id: "edge:finance-alegra", source: "node:toro-finance", target: "node:alegra", relation: "reads_from", verification: "partially_verified", freshness: "aging" },
    { id: "edge:kross-revenue", source: "node:kross", target: "node:revenue", relation: "produces", verification: "verified", freshness: "current" },
    { id: "edge:alegra-cash", source: "node:alegra", target: "node:cash", relation: "produces", verification: "partially_verified", freshness: "aging" },
    { id: "edge:evidence-cash", source: "node:bank-evidence", target: "node:cash", relation: "evidenced_by", verification: "verified", freshness: "current" },
    { id: "edge:construction-cash", source: "node:construction", target: "node:cash", relation: "depends_on", verification: "partially_verified", freshness: "aging" },
    { id: "edge:cash-decision", source: "node:cash", target: "node:decision", relation: "triggered_by", verification: "partially_verified", freshness: "aging" },
    { id: "edge:decision-approval", source: "node:decision", target: "node:capex-approval", relation: "requires_approval_from", verification: "unverified", freshness: "current" },
    { id: "edge:finance-decision", source: "node:toro-finance", target: "node:decision", relation: "produces", verification: "unverified", freshness: "current" },
  ],
  recentEvents: [
    {
      eventId: "event:1",
      occurredAt: "2026-09-22T23:44:08-06:00",
      scopeRef: "demo:dreamcatcher",
      actorKind: "agent",
      actorRef: "node:toro-finance",
      eventType: "source.read",
      entityKind: "connector",
      entityRef: "node:kross",
      summary: "Read the synthetic PMS reservation and collections snapshot.",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "Kross",
      risk: "Low",
      approvalState: "not_required",
      executionState: "completed",
      verificationState: "verified",
      evidenceRefs: [],
      redactionClass: "public_reference",
      correlationId: "demo:cash-gap:1",
    },
    {
      eventId: "event:2",
      occurredAt: "2026-09-22T23:44:12-06:00",
      scopeRef: "demo:dreamcatcher",
      actorKind: "agent",
      actorRef: "node:toro-finance",
      eventType: "source.read",
      entityKind: "connector",
      entityRef: "node:alegra",
      summary: "Read the synthetic accounting evidence and detected an aging source.",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "Alegra",
      risk: "Medium",
      approvalState: "not_required",
      executionState: "completed",
      verificationState: "partially_verified",
      evidenceRefs: [],
      redactionClass: "public_reference",
      correlationId: "demo:cash-gap:1",
    },
    {
      eventId: "event:3",
      occurredAt: "2026-09-22T23:44:16-06:00",
      scopeRef: "demo:dreamcatcher",
      actorKind: "agent",
      actorRef: "node:toro-finance",
      eventType: "risk.detected",
      entityKind: "kpi",
      entityRef: "node:cash",
      summary: "Detected that cash coverage is falling while booked revenue is rising.",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "TORO Brain",
      risk: "High",
      approvalState: "not_required",
      executionState: "completed",
      verificationState: "partially_verified",
      evidenceRefs: ["node:bank-evidence"],
      redactionClass: "public_reference",
      correlationId: "demo:cash-gap:1",
    },
    {
      eventId: "event:4",
      occurredAt: "2026-09-22T23:44:20-06:00",
      scopeRef: "demo:dreamcatcher",
      actorKind: "agent",
      actorRef: "node:toro-finance",
      eventType: "action.prepared",
      entityKind: "decision",
      entityRef: "node:decision",
      summary: "Prepared a cash-protection decision; no external change was executed.",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "TORO Brain",
      risk: "Medium",
      approvalState: "required",
      executionState: "approval_required",
      verificationState: "unverified",
      evidenceRefs: ["node:bank-evidence"],
      redactionClass: "public_reference",
      correlationId: "demo:cash-gap:1",
    },
    {
      eventId: "event:5",
      occurredAt: "2026-09-22T23:44:24-06:00",
      scopeRef: "demo:dreamcatcher",
      actorKind: "system",
      actorRef: "TORO Governance",
      eventType: "approval.requested",
      entityKind: "approval",
      entityRef: "node:capex-approval",
      summary: "Owner approval is required before discretionary CAPEX can change.",
      sourceSystem: "synthetic_fixture",
      authoritySystem: "TORO Governance",
      risk: "High",
      approvalState: "pending",
      executionState: "approval_required",
      verificationState: "unverified",
      evidenceRefs: ["node:bank-evidence"],
      redactionClass: "public_reference",
      correlationId: "demo:cash-gap:1",
    },
  ],
  sources: [
    { sourceSystem: "Kross", authoritySystem: "Kross", freshness: "current", verification: "verified", authoritative: true },
    { sourceSystem: "Alegra", authoritySystem: "Alegra", freshness: "aging", verification: "partially_verified", authoritative: true },
    { sourceSystem: "Bank evidence", authoritySystem: "Bank evidence", freshness: "current", verification: "verified", authoritative: true },
    { sourceSystem: "Synthetic fixture", authoritySystem: "TORO Brain demo", freshness: "current", verification: "verified", authoritative: false },
  ],
  partial: false,
};

export const visualBrainDemoLayout: Record<string, { x: number; y: number }> = {
  "node:dreamcatcher": { x: 50, y: 10 },
  "node:toro-finance": { x: 50, y: 34 },
  "node:kross": { x: 17, y: 34 },
  "node:alegra": { x: 83, y: 34 },
  "node:revenue": { x: 14, y: 64 },
  "node:cash": { x: 50, y: 58 },
  "node:bank-evidence": { x: 84, y: 63 },
  "node:construction": { x: 20, y: 88 },
  "node:decision": { x: 52, y: 84 },
  "node:capex-approval": { x: 83, y: 87 },
};
