import type { AgentProfile, AirtableTableModel, AuditEvent, BlueprintDocument, BusinessObject, Connector, ConnectorEndpoint, OperatingModule, QueuedAction, WorkspaceRole } from "./toro-types";

export const airtableBase = {
  id: "appFdcxw7KqReHJI6",
  name: "TORO OS - Master Brain",
  blueprintTableId: "tblHVdeHMb02gPxFP",
  blueprintTable: "31 TORO OS Build Blueprint",
  mainPromptRecord: "TORO OS Autonomous Business Operator Prompt v0.3 SAFE",
};

export const airtableTables: AirtableTableModel[] = [
  { id: "tblwWnTwkk9hc9rTU", name: "01 Source Registry", module: "Data Brain", authorityRole: "Defines source authority, risk, status and allowed use.", fields: [{ id: "fldjaJ5OEbT9I3Q3z", name: "Source Name", type: "singleLineText" }, { id: "fld0mSQTp5Cghv8qF", name: "Authority Level", type: "singleSelect" }, { id: "fldQA70Ive88TPdVC", name: "Risk Level", type: "singleSelect" }] },
  { id: "tblbYdTGHb37xNBS3", name: "02 Properties", module: "Business Brain", authorityRole: "Workspace/property map for Dreamcatcher and future businesses.", fields: [{ id: "fldz7UO1adqJE1wTQ", name: "Property Name", type: "singleLineText" }, { id: "fldecsmMLQvUY7ooa", name: "Operational Status", type: "singleSelect" }, { id: "fld9CkyXxGge32UAB", name: "Source Confidence", type: "number" }] },
  { id: "tblQvkQLvnIH3m7y9", name: "03 Villas", module: "Business Brain", authorityRole: "Canonical villa products and group experiences.", fields: [{ id: "fldOgrjAwCu1hcOV3", name: "Villa Name", type: "singleLineText" }, { id: "fldUwGZeAo4RukJVz", name: "Max Capacity", type: "number" }, { id: "fldgCd0O1qDwRU1hX", name: "Verified Status", type: "singleSelect" }] },
  { id: "tblKtS02fmm3btK3c", name: "04 Rooms", module: "Channel Content Control", authorityRole: "Canonical room content and commercial metadata.", fields: [{ id: "fldFRbHznL07aM013", name: "Room Key", type: "singleLineText" }, { id: "fldzATv2qhC3xpcwo", name: "Verified Status", type: "singleSelect" }, { id: "fld7tWBW8kmYFdK5p", name: "AI Use Permission", type: "singleSelect" }] },
  { id: "tbl9B3aVswGwQW23W", name: "05 Sellable Units", module: "Revenue & Pricing Control", authorityRole: "Sellable units; Kross remains live commercial authority.", fields: [{ id: "fldVt6FfqUtztBl0s", name: "Unit Key", type: "singleLineText" }, { id: "fldOsvkLGyNiJSBg3", name: "Kross Controlled", type: "checkbox" }, { id: "fldKsyMs92nIARozf", name: "Validation Status", type: "singleSelect" }] },
  { id: "tblVZP2eWR1yGbVAd", name: "06 Amenities", module: "Business Brain", authorityRole: "Guest promise guardrails and amenity scope.", fields: [{ id: "fldlxVoxsoBMZWQYT", name: "Amenity Name EN", type: "singleLineText" }, { id: "fldNGh7IdC129FySc", name: "Guest Expectation Risk", type: "singleSelect" }] },
  { id: "tbl5FfNnUMXVJ0S8r", name: "06A Experiences", module: "Campaign Studio", authorityRole: "Experience catalog for upsell and content planning.", fields: [{ id: "fldEPGDDVUpRP2FG0", name: "Experience Name", type: "singleLineText" }, { id: "fldqOvpz5rXy9rtQl", name: "Source Confidence", type: "number" }] },
  { id: "tblOfp0myygqqdR40", name: "07 Kross References", module: "Kross Control Center", authorityRole: "Reference mapping only; does not replace Kross.", fields: [{ id: "fldk1zOans8IFpIoT", name: "Kross Reference Key", type: "singleLineText" }, { id: "fldcezU3zFysQzsM3", name: "Kross Is Authority", type: "checkbox" }] },
  { id: "tblJnjzveR6agN0aw", name: "08 Assets Registry", module: "Assets Curation Pipeline", authorityRole: "Curated asset registry; Dropbox/Eagle original file authority.", fields: [{ id: "fldHmatutDJVCPJQ3", name: "Asset Name", type: "singleLineText" }, { id: "fld4kKTte7Uots5PK", name: "AI Commercial Grade", type: "singleSelect" }, { id: "fld46YTZzDcWPMSZd", name: "AI Curation Flags", type: "multipleSelects" }] },
  { id: "tbl9kwSOXRrA7wPai", name: "09 Website Pages", module: "Channel Content Control", authorityRole: "Approved or pending web page content.", fields: [{ id: "fldXGPFxgbWYwfbM3", name: "Page Name", type: "singleLineText" }, { id: "fldUlLmX52MH6c8AD", name: "Publish Status", type: "singleSelect" }] },
  { id: "tblYbGbMX2JLU80Fh", name: "10 Tasks", module: "Tasks & Approvals", authorityRole: "Operational, strategic and implementation tasks.", fields: [{ id: "fldumWv2NmThJJpT5", name: "Task Name", type: "singleLineText" }, { id: "fldJGDxOVq1qvYWbX", name: "Status", type: "singleSelect" }, { id: "fldsu0PXlWLUTXyzd", name: "Source", type: "singleSelect" }] },
  { id: "tbl0weguXrAL3MQ6N", name: "11 QA Conflicts", module: "Data Brain", authorityRole: "Conflicts, risky claims and human decisions.", fields: [{ id: "fld95WiV4PpZ268Mm", name: "Conflict Key", type: "singleLineText" }, { id: "fldBZwdWEWcoH1scN", name: "Human Validation Required", type: "checkbox" }] },
  { id: "tblyuG1Wc4Zk2vBET", name: "12 Governance Rules", module: "Governance/Rules Engine", authorityRole: "Authority, AI, privacy and publication rules.", fields: [{ id: "fldsycgMsAeFbS59d", name: "Rule Name", type: "singleLineText" }, { id: "fldqs4U3UyvTW1yJF", name: "Enforcement Level", type: "singleSelect" }] },
  { id: "tblJlkOarwAcJhxpE", name: "13 Guest Communication", module: "Communication Center", authorityRole: "Safe-copy and guest message drafts; no automatic sends.", fields: [{ id: "fldsoJOaIPMoBZV85", name: "Message Key", type: "singleLineText" }, { id: "fldpJS8DGQuR0pSdu", name: "Requires Human Review", type: "checkbox" }] },
  { id: "tblzL5L7lSQ2kS10t", name: "14 Guests / CRM Light", module: "Business Brain", authorityRole: "Light non-sensitive CRM context.", fields: [{ id: "fldlpIT1OmvtBeoTs", name: "Guest Key", type: "singleLineText" }, { id: "fldWGIsPcOBZodmEZ", name: "Privacy Flag", type: "checkbox" }] },
  { id: "tblm0vj8rIiIhUT21", name: "15 Reservations Snapshot", module: "Operations Floor", authorityRole: "Referential snapshot only; Kross remains authority.", fields: [{ id: "fldbquiVFuXUeoG66", name: "Reservation Key", type: "singleLineText" }, { id: "fldtKy3FpKCXjbtdI", name: "Kross Controlled", type: "checkbox" }] },
  { id: "tblv73Tw7GILs3f9X", name: "16 Operations", module: "Operations Floor", authorityRole: "Daily operations, incidents and follow-ups.", fields: [{ id: "fldeznCiW2A9AK9Np", name: "Operation Key", type: "singleLineText" }, { id: "fldPYBiGlL2FDVOIv", name: "Guest Impact", type: "singleSelect" }] },
  { id: "tblnBLOkPuJG8vX29", name: "17 Staff & Providers", module: "Operations Floor", authorityRole: "Staff/provider directory without sensitive finance data.", fields: [{ id: "fldUg8Wwb3KhuyDCV", name: "Contact Name", type: "singleLineText" }, { id: "fldRUz6aImxnEucUF", name: "Risk Level", type: "singleSelect" }] },
  { id: "tblf4FGF9I8wRBUnR", name: "18 SOPs / Policies", module: "Governance/Rules Engine", authorityRole: "Operating procedures and policy guidance.", fields: [{ id: "fld9m2XqAL6q83T7n", name: "SOP / Policy Name", type: "singleLineText" }, { id: "fldNNUy9JA1dcHJre", name: "Risk Level", type: "singleSelect" }] },
  { id: "tblR37RyWP1zxUVRP", name: "20 Kross BE Content Master", module: "Kross Control Center", authorityRole: "Booking engine content master; approved rows only.", fields: [{ id: "fldKKw3dDqawuTgAF", name: "Unit Key", type: "singleLineText" }, { id: "fldCqH5R2gmAvEqC9", name: "Kross Publish Status", type: "singleLineText" }] },
  { id: "tblZQmOvKBIDlocEG", name: "21 Website V11 Conversion OS", module: "Channel Content Control", authorityRole: "Conversion recommendations and build priorities.", fields: [{ id: "fldJNOw2hNq82zrbA", name: "Improvement Name", type: "singleLineText" }, { id: "fldAJ5JyDLLdr43Dz", name: "Priority Score", type: "number" }] },
  { id: "tblTJ0iuxYpLLMfYR", name: "30 V11 Master Control Center", module: "Codex Builder Queue", authorityRole: "Builder gates, QA and anti-pattern control.", fields: [{ id: "fldw8btSZtPD4jnJM", name: "Control Item", type: "singleLineText" }, { id: "fldRIq2z62pvkPy8J", name: "Builder Instruction", type: "multilineText" }] },
  { id: "tblHVdeHMb02gPxFP", name: "31 TORO OS Build Blueprint", module: "Codex Builder Queue", authorityRole: "Product blueprint, prompts and build governance.", fields: [{ id: "fldIBOnP1MW7xS94s", name: "Document Name", type: "singleLineText" }, { id: "fldqyjCJ8pdhYBNTQ", name: "Content", type: "multilineText" }] },
];

export const modules: OperatingModule[] = [
  { id: "command", name: "Command Home", purpose: "Daily business command: brief, risks, approvals, tasks and AI recommendations.", primaryObjects: ["Queued actions", "Approvals", "Tool health"], queuedActions: ["Review pricing recommendation", "Approve channel photo update"], actionLevel: "recommend", source: "31 TORO OS Build Blueprint", status: "Active", risk: "High", confidence: 96, approval: "Human review", nextAction: "Review queued actions before any execution." },
  { id: "brain", name: "Business Brain", purpose: "Universal map of workspaces, units, customers, services, assets and channels.", primaryObjects: ["Properties", "Villas", "Rooms", "Sellable Units"], queuedActions: ["Normalize unit facts", "Flag overpromised claims"], actionLevel: "analyze", source: "02-06A Airtable tables", status: "Review", risk: "Medium", confidence: 90, approval: "Human review", nextAction: "Validate room/unit facts against source confidence." },
  { id: "tools", name: "Tool Hub/Connector Center", purpose: "Connector registry and readiness center for APIs, OAuth, imports, browser-assisted tools and manual links.", primaryObjects: ["Airtable", "Kross", "Dropbox", "OpenAI", "Codex", "Vercel"], queuedActions: ["Test read connector", "Request OAuth scope"], actionLevel: "observe", source: "Source Registry + v0.3 prompt", status: "Ready", risk: "High", confidence: 88, approval: "Owner approval", nextAction: "Keep all connectors read-only until permission gates exist." },
  { id: "agents", name: "Agent Command Center", purpose: "Agent roles, memory, tool access, allowed actions, blocked actions and logs.", primaryObjects: ["Agent profiles", "Permission ceilings", "Audit logs"], queuedActions: ["Run agent simulation", "Create policy test"], actionLevel: "draft", source: "Governance Rules", status: "Draft", risk: "Critical", confidence: 84, approval: "Owner approval", nextAction: "Validate agent permissions against action matrix." },
  { id: "revenue", name: "Revenue & Pricing Control", purpose: "Prepare pricing recommendations from market and unit context without changing live prices.", primaryObjects: ["Sellable Units", "Kross references", "Market signals"], queuedActions: ["Prepare rate note", "Queue Kross review"], actionLevel: "recommend", source: "Kross + Airtable", status: "Queued", risk: "Critical", confidence: 82, approval: "Owner approval", nextAction: "Compare recommendation with live Kross before approval." },
  { id: "campaigns", name: "Campaign Studio", purpose: "Prepare campaigns, captions, assets, channels and approval packages.", primaryObjects: ["Campaigns", "Assets", "Experiences", "Channels"], queuedActions: ["Draft Instagram carousel", "Prepare WhatsApp broadcast"], actionLevel: "draft", source: "Assets Registry + Experiences", status: "Active", risk: "Medium", confidence: 89, approval: "Human review", nextAction: "Attach approved assets and request review." },
  { id: "channel", name: "Channel Content Control", purpose: "Website, booking engine, OTA and social content/photo updates prepared for approval.", primaryObjects: ["Website Pages", "Kross BE Content", "Conversion OS"], queuedActions: ["Prepare Kross copy fields", "Create Codex task"], actionLevel: "prepare_fields", source: "20 Kross BE Content Master", status: "Review", risk: "High", confidence: 91, approval: "Owner approval", nextAction: "Queue publish package, do not write externally." },
  { id: "market", name: "Market Research Center", purpose: "Research competitors, channel opportunities and pricing context for recommendations.", primaryObjects: ["Research briefs", "Competitor notes", "Market signals"], queuedActions: ["Create Santa Teresa comp set brief"], actionLevel: "analyze", source: "Prepared research scaffold", status: "Draft", risk: "Medium", confidence: 74, approval: "Human review", nextAction: "Connect approved research sources." },
  { id: "kross", name: "Kross Control Center", purpose: "Booking engine content and Kross reference QA while Kross remains live authority.", primaryObjects: ["Kross IDs", "Public URLs", "Publish status"], queuedActions: ["Review room URL health", "Prepare content update"], actionLevel: "observe", source: "07 + 20 Airtable tables", status: "Active", risk: "Critical", confidence: 92, approval: "Owner approval", nextAction: "Read public URLs only; block direct Kross writes." },
  { id: "comm", name: "Communication Center", purpose: "Guest safe-copy, channel drafts, review flags and escalation paths.", primaryObjects: ["Guest Communication", "CRM Light"], queuedActions: ["Draft reply", "Escalate risky claim"], actionLevel: "draft", source: "13 Guest Communication", status: "Review", risk: "High", confidence: 87, approval: "Human review", nextAction: "Require review for guest-facing messages." },
  { id: "ops", name: "Operations Floor", purpose: "Daily operations, housekeeping, maintenance, guest issues and follow-ups.", primaryObjects: ["Operations", "Reservations Snapshot", "SOPs"], queuedActions: ["Assign follow-up", "Prepare incident summary"], actionLevel: "queue_task", source: "16 Operations", status: "Active", risk: "Medium", confidence: 86, approval: "Human review", nextAction: "Queue work order; external notifications disabled." },
  { id: "assets", name: "Assets Curation Pipeline", purpose: "Commercial asset grading, hero candidates, photo validation and content mapping.", primaryObjects: ["Assets", "Rooms", "Villas", "Experiences"], queuedActions: ["Select hero candidate", "Flag weak gallery"], actionLevel: "recommend", source: "08 Assets Registry", status: "Review", risk: "Medium", confidence: 83, approval: "Human review", nextAction: "Approve photo set before channel update." },
  { id: "data", name: "Data Brain", purpose: "Source authority monitor, conflicts, confidence, data class and public/private boundaries.", primaryObjects: ["Source Registry", "QA Conflicts", "Governance"], queuedActions: ["Resolve conflict", "Lower AI permission"], actionLevel: "analyze", source: "01 + 11 Airtable tables", status: "Active", risk: "High", confidence: 94, approval: "Human review", nextAction: "Resolve critical source conflicts before action." },
  { id: "gov", name: "Governance/Rules Engine", purpose: "User + Agent + Tool + Action + Data Type = allowed, approval required or blocked.", primaryObjects: ["Rules", "Roles", "Approval gates"], queuedActions: ["Evaluate policy", "Block sensitive action"], actionLevel: "blocked", source: "12 Governance Rules", status: "Active", risk: "Critical", confidence: 98, approval: "Owner approval", nextAction: "Enforce no external writes in v0.3." },
  { id: "approvals", name: "Tasks & Approvals", purpose: "Central review queue for operations, campaign, content and builder actions.", primaryObjects: ["Tasks", "Approvals", "Logs"], queuedActions: ["Approve draft", "Reject unsafe action"], actionLevel: "queue_task", source: "10 Tasks", status: "Active", risk: "High", confidence: 91, approval: "Owner approval", nextAction: "Route every sensitive action through queue." },
  { id: "browser", name: "Browser Control", purpose: "Assisted browser mode for tools without APIs; guide, draft, fill and submit only with approval.", primaryObjects: ["Browser sessions", "Checklists", "Action log"], queuedActions: ["Open tool in assisted mode", "Prepare copy/paste fields"], actionLevel: "prepare_fields", source: "v0.3 SAFE prompt", status: "Draft", risk: "Critical", confidence: 80, approval: "Owner approval", nextAction: "Keep submit actions blocked until approval flow is live." },
  { id: "codex", name: "Codex Builder Queue", purpose: "Create code tasks, preview checks, Vercel deployment status and build governance.", primaryObjects: ["Blueprint", "Builder tasks", "Preview gates"], queuedActions: ["Create Codex task", "Review Vercel preview"], actionLevel: "queue_task", source: "31 TORO OS Build Blueprint", status: "Ready", risk: "Medium", confidence: 93, approval: "Human review", nextAction: "Queue tasks; no automatic repo mutations beyond builder approval." },
  { id: "settings", name: "Settings/Workspaces/Roles", purpose: "Workspace templates, roles, permissions and connector settings.", primaryObjects: ["Workspaces", "Roles", "Policies"], queuedActions: ["Create role", "Scope connector"], actionLevel: "draft", source: "v0.2 data mapping", status: "Draft", risk: "High", confidence: 86, approval: "Owner approval", nextAction: "Define role matrix before live connectors." },
];

export const connectors: Connector[] = [
  { id: "airtable", name: "Airtable", category: "Data", mode: "MCP/read adapter", authority: "Structured business/content brain", currentCapability: "Read source schemas and records through connector", futureConnectorNeed: "Scoped read/write adapter with audit logs", allowedActions: ["observe", "analyze", "draft", "queue_task"], source: "01 Source Registry", status: "Active", risk: "High", confidence: 96, approval: "Human review", nextAction: "Keep writes disabled in v0.3." },
  { id: "kross", name: "Kross PMS", category: "Commercial authority", mode: "Public URL reader + browser assisted mode", authority: "Live prices, availability, reservations and restrictions", currentCapability: "Reference mapping and public URL review only", futureConnectorNeed: "Confirmed API/webhook or approved browser workflow", allowedActions: ["observe", "analyze", "recommend"], source: "07 Kross References", status: "Review", risk: "Critical", confidence: 92, approval: "Owner approval", nextAction: "Block direct price, availability and reservation changes." },
  { id: "dropbox", name: "Dropbox / Eagle", category: "Media", mode: "File resolver/import", authority: "Original media archive", currentCapability: "Curated registry and source path mapping", futureConnectorNeed: "Asset resolver, signed previews, rights metadata", allowedActions: ["observe", "analyze", "recommend"], source: "08 Assets Registry", status: "Review", risk: "Medium", confidence: 88, approval: "Human review", nextAction: "Approve commercial-grade photo sets." },
  { id: "openai", name: "OpenAI", category: "Reasoning", mode: "API scaffold", authority: "Agent reasoning only", currentCapability: "No live calls in this static foundation", futureConnectorNeed: "Server-side agent routes with policy checks", allowedActions: ["analyze", "draft", "recommend", "queue_task"], source: "v0.3 SAFE prompt", status: "Draft", risk: "High", confidence: 84, approval: "Owner approval", nextAction: "Add guarded server routes after roles are defined." },
  { id: "codex", name: "Codex", category: "Builder", mode: "Task queue", authority: "Code builder", currentCapability: "Queue builder tasks and preview checks", futureConnectorNeed: "GitHub issue/PR integration", allowedActions: ["draft", "queue_task"], source: "31 Build Blueprint", status: "Ready", risk: "Medium", confidence: 90, approval: "Human review", nextAction: "Convert approved content work into builder tasks." },
  { id: "vercel", name: "Vercel", category: "Deployment", mode: "Preview authority", authority: "Deployments and previews", currentCapability: "Manual preview deployment", futureConnectorNeed: "Deployment status adapter", allowedActions: ["observe"], source: "v0.3 SAFE prompt", status: "Ready", risk: "Medium", confidence: 89, approval: "Human review", nextAction: "Deploy preview and log URL." },
  { id: "whatsapp", name: "WhatsApp / WeSpeak", category: "Communication", mode: "Draft handoff", authority: "Guest messaging channel", currentCapability: "Drafts only", futureConnectorNeed: "Approved send adapter and escalation policy", allowedActions: ["draft", "queue_task"], source: "13 Guest Communication", status: "Not connected", risk: "Critical", confidence: 78, approval: "Owner approval", nextAction: "Never auto-send in v0.3." },
  { id: "social", name: "Instagram / TikTok / Meta / GBP", category: "Channels", mode: "Campaign draft planner", authority: "External channel publishing", currentCapability: "Captions, assets and approval packages", futureConnectorNeed: "OAuth publishing behind approval gates", allowedActions: ["draft", "recommend", "queue_task"], source: "Campaign Studio scaffold", status: "Draft", risk: "High", confidence: 82, approval: "Owner approval", nextAction: "Prepare campaign, do not publish." },
  { id: "alegra", name: "Alegra", category: "Accounting", mode: "Not connected", authority: "Accounting authority when connected", currentCapability: "No finance writes", futureConnectorNeed: "Read-only accounting adapter first", allowedActions: ["observe"], source: "v0.3 SAFE prompt", status: "Blocked", risk: "Critical", confidence: 70, approval: "Owner approval", nextAction: "Block invoices, charges, refunds and accounting writes." },
];

export const businessObjects: BusinessObject[] = [
  { id: "dc", type: "Property", name: "Dreamcatcher Hotel", owner: "Mauricio Fernandez Toro", details: "First workspace/demo; central Santa Teresa hospitality operation with high source confidence.", source: "02 Properties", status: "Active", risk: "Medium", confidence: 95, approval: "Human review", nextAction: "Use as first workspace while keeping universal architecture." },
  { id: "vt", type: "Villa", name: "Villa Toro", owner: "Dreamcatcher", details: "New premium villa, completed January 2026, 8 rooms, max 29, Kross public content ready.", source: "03 Villas", status: "Ready", risk: "High", confidence: 95, approval: "Owner approval", nextAction: "Prepare channel content updates; validate price/availability in Kross." },
  { id: "mkz", type: "Villa", name: "Makaiza", owner: "Dreamcatcher", details: "Secret multi-level villa for groups, up to 15-20 on request and validation.", source: "03 Villas", status: "Review", risk: "Medium", confidence: 90, approval: "Human review", nextAction: "Keep flexible/on-request language." },
  { id: "buyout", type: "Villa", name: "Dreamcatcher Full Property Buyout", owner: "Dreamcatcher", details: "Flexible full-property group experience from 6 to around 70 guests by validation.", source: "03 Villas", status: "Draft", risk: "High", confidence: 88, approval: "Owner approval", nextAction: "Do not promise exact configuration, price or availability." },
  { id: "kross-content", type: "Content", name: "Kross BE Content Master", owner: "TORO OS", details: "Multilingual room/unit content, public URLs, publish status and QA notes.", source: "20 Kross BE Content Master", status: "Review", risk: "High", confidence: 91, approval: "Owner approval", nextAction: "Queue Kross copy packages for approval only." },
  { id: "assets", type: "Asset", name: "Commercial Photo Pipeline", owner: "TORO OS", details: "Hero candidates, gallery order, detected subject and AI curation flags.", source: "08 Assets Registry", status: "Review", risk: "Medium", confidence: 83, approval: "Human review", nextAction: "Approve assets before channel use." },
];

export const queuedActions: QueuedAction[] = [
  { id: "qa-001", title: "Prepare Villa Toro Kross photo/content update", module: "Channel Content Control", targetTool: "Kross Booking Engine", actionLevel: "prepare_fields", impact: "External guest-facing content if approved", log: ["Draft only", "Requires owner approval", "No Kross write performed"], source: "20 Kross BE Content Master", status: "Queued", risk: "Critical", confidence: 88, approval: "Owner approval", nextAction: "Review copy/photo package." },
  { id: "qa-002", title: "Create Codex task for booking engine content preview", module: "Codex Builder Queue", targetTool: "Codex/GitHub", actionLevel: "queue_task", impact: "Creates implementation work item after review", log: ["Prepared from Airtable blueprint", "Awaiting approval"], source: "31 TORO OS Build Blueprint", status: "Ready", risk: "Medium", confidence: 92, approval: "Human review", nextAction: "Approve builder task scope." },
  { id: "qa-003", title: "Draft WhatsApp reply for group buyout inquiry", module: "Communication Center", targetTool: "WhatsApp / WeSpeak", actionLevel: "draft", impact: "Guest-facing text if sent manually", log: ["Uses on-request language", "Blocks price/availability promises"], source: "13 Guest Communication + 03 Villas", status: "Review", risk: "High", confidence: 86, approval: "Human review", nextAction: "Human reviews before sending." },
  { id: "qa-004", title: "Revenue recommendation for high-demand weekend", module: "Revenue & Pricing Control", targetTool: "Kross PMS", actionLevel: "recommend", impact: "Pricing advice only; no live rate change", log: ["Kross is authority", "Recommendation only"], source: "Kross References + Market Research", status: "Draft", risk: "Critical", confidence: 74, approval: "Owner approval", nextAction: "Compare with live Kross and market comps." },
];

export const blueprintDocuments: BlueprintDocument[] = [
  {
    id: "recEK2AD2Udqp1qf5",
    name: "TORO OS Autonomous Business Operator Prompt v0.3 SAFE",
    version: "v0.3 SAFE",
    role: "Primary operating prompt",
    summary: "Defines TORO OS as the AI operating brain with approval gates, business understanding, research, connector prep and queued actions.",
    source: "31 TORO OS Build Blueprint",
    status: "Active",
    risk: "High",
    confidence: 98,
    approval: "Owner approval",
    nextAction: "Keep as the single main prompt for v0.3 builds.",
  },
  {
    id: "recmJi0ErKRquI8DG",
    name: "TORO OS Operational Build Prompt v0.2",
    version: "v0.2",
    role: "Build context",
    summary: "Earlier build framing that still informs module scope, safety boundaries and implementation sequencing.",
    source: "31 TORO OS Build Blueprint",
    status: "Review",
    risk: "Medium",
    confidence: 90,
    approval: "Human review",
    nextAction: "Use for reference only where it does not conflict with v0.3 SAFE.",
  },
  {
    id: "recFoHJjTvdaIqUr2",
    name: "TORO OS Airtable Data Mapping v0.2",
    version: "v0.2",
    role: "Data contract reference",
    summary: "Maps business objects, authorities and table responsibilities used to shape the TypeScript model and mock data.",
    source: "31 TORO OS Build Blueprint",
    status: "Active",
    risk: "Medium",
    confidence: 94,
    approval: "Human review",
    nextAction: "Keep table contracts aligned with this mapping as live reads expand.",
  },
  {
    id: "rec5KZUQ6CasrrVrr",
    name: "TORO OS Codex Readiness Checklist v0.2",
    version: "v0.2",
    role: "Execution checklist",
    summary: "Defines repo mirrors, data typing, mock shape fidelity and deployment expectations before deeper automation.",
    source: "31 TORO OS Build Blueprint",
    status: "Ready",
    risk: "Medium",
    confidence: 93,
    approval: "Human review",
    nextAction: "Use as the implementation gate before adding live connectors or agent routes.",
  },
];

export const agentProfiles: AgentProfile[] = [
  { id: "operator", name: "Business Operator Framework", role: "Coordinates daily brief, tasks, approvals and tool health.", memoryScope: "Workspace operational memory only", dataAccess: ["Airtable business brain", "Governance rules", "Tasks"], toolAccess: ["Airtable read", "Codex queue", "Vercel status"], allowedActions: ["observe", "analyze", "draft", "recommend", "queue_task"], blockedActions: ["External writes", "Payments", "Price changes", "Reservations"], source: "v0.3 SAFE prompt", status: "Draft", risk: "High", confidence: 86, approval: "Owner approval", nextAction: "Run simulation against governance rules." },
  { id: "revenue", name: "Revenue Analyst Framework", role: "Prepares pricing and channel recommendations.", memoryScope: "Commercial context, no live authority", dataAccess: ["Sellable Units", "Kross References", "Market Research"], toolAccess: ["Kross public URL reader"], allowedActions: ["observe", "analyze", "recommend"], blockedActions: ["Change rates", "Change availability", "Cancel reservations"], source: "v0.3 SAFE prompt", status: "Draft", risk: "Critical", confidence: 78, approval: "Owner approval", nextAction: "Keep all recommendations approval-gated." },
  { id: "content", name: "Channel Content Framework", role: "Prepares copy, photo selections and campaign packages.", memoryScope: "Approved content and asset metadata", dataAccess: ["Assets Registry", "Website Pages", "Kross Content"], toolAccess: ["Dropbox resolver", "Codex queue"], allowedActions: ["draft", "recommend", "prepare_fields", "queue_task"], blockedActions: ["Publish social", "Write Kross", "Delete media"], source: "v0.2 mapping", status: "Review", risk: "High", confidence: 84, approval: "Human review", nextAction: "Validate source and photo rights before approval." },
];

export const safetyModel = [
  "No direct external writes in v0.3.",
  "Kross controls live prices, availability, restrictions, payments and confirmed reservations.",
  "Airtable/TORO OS is the structured business and content brain.",
  "Dropbox/Eagle remains original media authority.",
  "Sensitive actions are approval-gated or blocked: publishing, price changes, availability, cancellations, invoices, charges, refunds, deletes and guest messages.",
  "Every action logs source, status, risk, confidence, approval requirement and next action.",
];

export const workspaceRoles: WorkspaceRole[] = [
  {
    id: "role-owner",
    workspace: "Dreamcatcher Hotel",
    role: "Owner",
    permissions: ["approve_high_risk", "approve_connector_scope", "review_pricing", "review_guest_copy"],
    blocked: ["bypass_audit_log", "share_secrets_in_airtable"],
    approvalLimit: "Owner approval",
    source: "12 Governance Rules",
  },
  {
    id: "role-operator",
    workspace: "Dreamcatcher Hotel",
    role: "Operator",
    permissions: ["queue_task", "draft_message", "prepare_content", "observe_connector"],
    blocked: ["change_price", "publish_social", "send_whatsapp", "cancel_reservation"],
    approvalLimit: "Human review",
    source: "v0.3 SAFE prompt",
  },
  {
    id: "role-builder",
    workspace: "TORO OS",
    role: "Builder",
    permissions: ["create_codex_task_draft", "inspect_preview", "prepare_pull_request_scope"],
    blocked: ["deploy_without_review", "write_external_business_tool"],
    approvalLimit: "Human review",
    source: "31 TORO OS Build Blueprint",
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "log-001",
    event: "Vercel preview deployment recorded",
    actor: "Codex",
    target: "toro-os-v03 preview",
    timestamp: "2026-06-09T09:00:00.000Z",
    outcome: "observed",
    source: "Vercel CLI",
    status: "Ready",
    risk: "Medium",
    confidence: 92,
    approval: "Human review",
    nextAction: "Review preview before production use.",
  },
  {
    id: "log-002",
    event: "Kross update converted into approval package",
    actor: "TORO OS",
    target: "Villa Toro Kross content",
    timestamp: "2026-06-09T09:05:00.000Z",
    outcome: "prepared",
    source: "20 Kross BE Content Master",
    status: "Queued",
    risk: "Critical",
    confidence: 88,
    approval: "Owner approval",
    nextAction: "Owner reviews copy/photo package.",
  },
  {
    id: "log-003",
    event: "WhatsApp send blocked; draft only",
    actor: "Communication Center",
    target: "Group buyout inquiry",
    timestamp: "2026-06-09T09:10:00.000Z",
    outcome: "blocked",
    source: "13 Guest Communication",
    status: "Blocked",
    risk: "High",
    confidence: 86,
    approval: "Human review",
    nextAction: "Human reviews and sends manually if approved.",
  },
];

export const connectorEndpoints: ConnectorEndpoint[] = [
  {
    id: "endpoint-approvals",
    name: "Approvals persistence seed",
    route: "/api/approvals",
    method: "GET",
    mode: "read_only",
    envRequired: [],
    externalWrite: false,
    source: "10 Tasks + local persistence",
    status: "Ready",
    risk: "Medium",
    confidence: 90,
    approval: "Human review",
    nextAction: "Persist user decisions client-side until database is connected.",
  },
  {
    id: "endpoint-agent",
    name: "Guarded OpenAI agent preparation",
    route: "/api/agent/prepare",
    method: "POST",
    mode: "prepare_only",
    envRequired: ["OPENAI_API_KEY for future live reasoning"],
    externalWrite: false,
    source: "v0.3 SAFE prompt",
    status: "Ready",
    risk: "High",
    confidence: 84,
    approval: "Owner approval",
    nextAction: "Return guarded draft; do not execute external actions.",
  },
  {
    id: "endpoint-airtable",
    name: "Airtable read adapter",
    route: "/api/connectors/airtable",
    method: "GET",
    mode: "read_only",
    envRequired: ["AIRTABLE_TOKEN", "AIRTABLE_BASE_ID"],
    externalWrite: false,
    source: "01 Source Registry",
    status: "Draft",
    risk: "High",
    confidence: 82,
    approval: "Human review",
    nextAction: "Connect read scopes only.",
  },
  {
    id: "endpoint-vercel",
    name: "Vercel deployment status adapter",
    route: "/api/connectors/vercel",
    method: "GET",
    mode: "read_only",
    envRequired: ["VERCEL_TOKEN", "VERCEL_PROJECT_ID"],
    externalWrite: false,
    source: "Vercel preview authority",
    status: "Draft",
    risk: "Medium",
    confidence: 80,
    approval: "Human review",
    nextAction: "Read deployment status and log preview URL.",
  },
  {
    id: "endpoint-codex",
    name: "GitHub/Codex task creation scaffold",
    route: "/api/connectors/github-codex",
    method: "POST",
    mode: "prepare_only",
    envRequired: ["GITHUB_TOKEN for future issue creation"],
    externalWrite: false,
    source: "31 TORO OS Build Blueprint",
    status: "Ready",
    risk: "Medium",
    confidence: 86,
    approval: "Human review",
    nextAction: "Prepare task payload; do not create issue until approved.",
  },
  {
    id: "endpoint-dropbox",
    name: "Dropbox asset resolver scaffold",
    route: "/api/connectors/dropbox",
    method: "POST",
    mode: "prepare_only",
    envRequired: ["DROPBOX_ACCESS_TOKEN for future signed links"],
    externalWrite: false,
    source: "08 Assets Registry",
    status: "Draft",
    risk: "Medium",
    confidence: 78,
    approval: "Human review",
    nextAction: "Resolve asset references after rights approval.",
  },
];
